all:
	javac -cp "peersim-lib/*"  GanciSimulazione/DSR_IOT/*.java GanciSimulazione/DSR_IOT/path/*.java GanciSimulazione/DSR_IOT/query/*.java GanciSimulazione/DSR_IOT/nodeInfo/*.java GanciSimulazione/network/*.java 
clean:
	 del /s *.class
